name: Deploy Blog

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Configure pnpm
        run: pnpm config set strict-peer-dependencies false
      # 원하는 Github Secrets을 불러와 env 파일을 생성해줍니다.
      - name: Generate env file
        run: |
          echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env
          echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      - name: Install dependencies
        run: pnpm install
      - name: Deploy gatsby
        uses: peaceiris/actions-gh-pages@v3
        with:
          access-token: ${{ secrets.DEPLOYMENT_ACCESS_TOKEN }}
          deploy-branch: main
          gatsby-args: --verbose
